### PR TITLE
1.16.0

### LINKED ISSUE #3: Default to only down app bundle and default to db search engine
Beginning in version 1.16.0, db search will be default and we can modify the fast path to only download the search bundle if requested. 

Tasks
- [x] add flag to install scripts to ask for search, default will be no
- [ ] update fast path install guide in doc
- [x] update readme here to provide examples of how to call it
- [ ] review download page on brochure site to see if it needs changes

### PR DESCRIPTION
**Pull request by tyduptyler13**
Dependencies:
* `1.16.0` is released - This script depends on `1.16.0` GA because release candidates are not returned by the latest version API. This means that the script would try to install `1.15.8` without a search engine by default which would break installs.

Required steps:

* [ ] Do full test using url (you can modify the url to point at the branch and it will be equivalent)
* [ ] Merge this branch
* [ ] Update site to reflect new windows install method
* [ ] Update doc to reflect new windows install method

Closes #3

### CODE REVIEW

**Comment by robotdan** [comment]
1.16.0 is out. Should be un-blocked.

**Comment by robotdan** [comment]
@tyduptyler13 @trex What is left to get all of the install stuff working for 1.16.0? Can I help push it over the finish line?

**Comment by tyduptyler13** [comment]
I can run the test real quick now that 1.16.0 is out. Then we can merge this branch and its done.

**Comment by tyduptyler13** [comment]
I tested the scripts, windows works, linux needed some tweaks but works now. If you would like to test it as well you can, otherwise I think its ready to merge.

**Comment by tyduptyler13** [comment]
Once its merged you can copy the new install commands from the readme.

**Comment by robotdan** [comment]
Ok, so ready to go essentially? Did you review the comments on the files, or do I need to handle those changes after the merge?

**Comment by tyduptyler13** [comment]
Yeah, I think we are ready to go. All the tests look good. The process was nearly identical to prod so I don't expect any issues. The comments in the files also are updated but feel free to change them if you feel they aren't explicit enough.

**Pull request merged**
